name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

jobs:
  update:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.3
        with:
          deno-version: v1.38.5
      - name: Update README
        run: make generate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      - name: Commit changes
        continue-on-error: true
        run: make persist
